### ISSUE TITLE
Merge `manytrade::code_countryname` function with existing functions in other many packages

### ISSUE THREAD

**Issue by jaeltan** [globalgov/manytrade#19]
Currently `manytrade::code_countryname()`, `manystates::code_states()`, and `manypkgs::code_parties()` serve similar purposes. We can look into combining the regex lists and the different aspects of the functions to be more concise in our usage across the packages.

**Comment by henriquesposito** [comment]
I have deleted `code_coutryame()` in manytrade and added an "abbrev" argument for `code_states()` in manystates . This made the functions very similar so there was no need for both. As for `code_parties()` in manypkgs, the function returns only parties for bilateral treaties. As such, I think we can leave code_states()` in manystates and `code_parties()` in manypkgs for now, as we had beforehand. @BBieri what do you think? Thank you.

**Comment by BBieri** [comment]
Looks all good to me! Thanks for the work @henriquesposito :)
