### ISSUE TITLE
Check rendered README.md files are committed

### ISSUE THREAD

**Issue by jaeltan** [globalgov/manytrade#21]
During release there was an error in committing the rendered README.md files for both manytrade and manydata.

**Comment by jaeltan** [comment]
From GitHub actions for manytrade PR:

Run git add README.md
[main da21fce] Re-build README.md
 Committer: runner <runner@Mac-1638530423455.local>
 1 file changed, 16 insertions(+), 18 deletions(-)
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/globalgov/manytrade'
No changes to commit

**Comment by BBieri** [comment]
Note to self:

It's solved! Basically what happened was that the default `{usethis}` template has a commit message pushing the master branch and not the main branch we have. See this [guide for more](https://fromthebottomoftheheap.net/2020/04/30/rendering-your-readme-with-github-actions/).
