### ISSUE TITLE
Treaty and linkage are equal for manyID in HUGGO_mem

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manytrade#39]
For example, manyIDs might be "SI04HN2010A:SI04HN2010A" which should not happen...

**Comment by henriquesposito** [comment]
@jaeltan I am not able to find these occurrences in the data. Could you please share the code or add the duplicated cases here? Thank you.

**Comment by jaeltan** [comment]
I believe this issue was already resolved before when we were working on the manyIDs, I'm not sure why this issue was opened...
